import bcrypt from 'bcryptjs';
import prisma from '../../backend/config/db.js';

const defaultVehicles = [
  {
    name: 'JAC T9 Hunter',
    fullTitle: 'JAC T9 Hunter 4x4',
    slug: 't9-hunter',
    tagline: 'Flagship 2.0L Turbo Diesel 8-Speed Auto Pickup',
    category: 'PASSENGERS',
    subcategory: null,
    categoryLabel: 'Passenger',
    status: 'Published',
    isFlagship: true,
    isNew: true,
    mainImage: 'https://res.cloudinary.com/lg7mgh99/image/upload/v1790056540/jac_motors/vehicle_t9-hunter_main.jpg',
    heroImage: 'https://res.cloudinary.com/lg7mgh99/image/upload/v1790056540/jac_motors/vehicle_t9-hunter_hero.jpg',
    altText: 'JAC Vehicle',
    gallery: JSON.stringify([
      'https://res.cloudinary.com/lg7mgh99/image/upload/v1790056540/jac_motors/vehicle_t9-hunter_main.jpg',
      'https://res.cloudinary.com/lg7mgh99/image/upload/v1790056540/jac_motors/vehicle_t9-hunter_gal_2.jpg',
      'https://res.cloudinary.com/lg7mgh99/image/upload/v1790056540/jac_motors/vehicle_t9-hunter_gal_3.jpg',
    ]),
    colorOptions: JSON.stringify([
      { name: 'Titanium Metallic Gray', hex: '#374151' },
      { name: 'Crimson Red', hex: '#C8102E' },
      { name: 'Onyx Black', hex: '#111827' },
      { name: 'Polar White', hex: '#FFFFFF' },
    ]),
    overview: 'The JAC T9 Hunter double cabin pickup is designed for high-performance off-road capability, heavy payload towing, and executive passenger comfort. Powered by a 2.0L CTI Turbocharged Diesel engine paired with an 8-Speed ZF Automatic Transmission and Electronic 4WD, the T9 Hunter excels on tough terrain while providing a premium cabin experience.',
    specs: JSON.stringify({
      engine: '2.0L CTI 4-Cylinder Turbo Diesel',
      displacement: '1999 cc',
      horsepower: '170 HP @ 3600 RPM',
      torque: '410 Nm @ 1500-2500 RPM',
      transmission: '8-Speed Automatic',
      driveType: 'Electronic 4WD (2H / 4H / 4L)',
      fuelType: 'Diesel',
      seatingCapacity: 5,
      payloadCapacityKg: 1000,
      towingCapacityKg: 'To be confirmed by dealership',
      dimensions: '5330 mm (L) x 1965 mm (W) x 1920 mm (H)',
      wheelbase: '3110 mm',
      fuelTankCapacityLiters: 76,
      safetySummary: '7 Airbags, 360 Camera, Bosch 9.3 ESP, TPMS',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Performance & Drivetrain',
        features: [
          '8-Speed ZF Automatic Transmission',
          'Electronic 4x4 Transfer Case',
          'Rear Differential Lock System',
          'Multi-Link Rear Suspension',
          '18" Alloy Wheels',
        ],
      },
      {
        categoryName: 'Safety & Electronics',
        features: [
          '7 Airbags (Front, Side, Curtain, Knee)',
          '360-Degree Panoramic View Camera',
          'Bosch Electronic Stability Program (ESP)',
          'Hill Descent Control & Hill Start Assist',
          'Tire Pressure Monitoring System (TPMS)',
        ],
      },
      {
        categoryName: 'Interior & Convenience',
        features: [
          '10.4-inch HD Touchscreen with Smartphone Connectivity',
          '7-inch Digital Driver Display Instrument Cluster',
          'Leather Seats with Power Adjustment',
          'Automatic Dual-Zone Climate Control',
          'Power Sunroof & Wireless Phone Charging Pad',
        ],
      },
    ]),
    whyT9Benefits: JSON.stringify([
      { title: 'Capability', description: 'Engineered for demanding terrain and passenger comfort with 410 Nm torque and Electronic 4WD.', icon: 'Truck' },
      { title: 'Comfort', description: 'Refined interior layout featuring quiet cabin noise insulation, leather seating, and digital controls.', icon: 'Sparkles' },
      { title: 'Practicality', description: '1,000 kg payload bed capacity paired with high-efficiency 2.0L diesel fuel economy.', icon: 'ShieldCheck' },
      { title: 'Modern Design', description: 'Bold front grille stance, sleek LED lighting signature, and aerodynamically optimized body profile.', icon: 'Wrench' },
    ]),
    warranty: '3 Years / 100,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/jac-t9-hunter-brochure.pdf',
    seoTitle: 'JAC T9 Hunter Double Cabin Pickup | Khyber Motors',
    metaDescription: 'Discover the flagship JAC T9 Hunter 2.0L Turbo Diesel 8-Speed 4x4 pickup. Experience top performance, luxury interior, and high payload capacity.',
  },
  {
    name: 'JAC T9 Frison',
    fullTitle: 'JAC T9 Frison Double Cabin Pickup',
    slug: 't9-frison',
    tagline: 'Reliable & Versatile Double Cabin Passenger Pickup',
    category: 'PASSENGERS',
    subcategory: null,
    categoryLabel: 'Passenger',
    status: 'Published',
    isFlagship: false,
    isNew: false,
    mainImage: '',
    heroImage: '',
    altText: 'JAC Vehicle',
    gallery: JSON.stringify([]),
    colorOptions: JSON.stringify([
      { name: 'Commercial White', hex: '#FFFFFF' },
      { name: 'Granite Gray', hex: '#4B5563' },
      { name: 'Onyx Black', hex: '#111827' },
    ]),
    overview: 'The versatile JAC T9 Frison double cabin pickup features a durable diesel powertrain, reinforced rear suspension, and a spacious 5-seater cabin arrangement for corporate fleet work and passenger transport.',
    specs: JSON.stringify({
      engine: '2.0L Turbo Diesel Engine',
      displacement: '1999 cc',
      horsepower: '138 HP @ 3600 RPM',
      torque: '320 Nm @ 2000 RPM',
      transmission: '5-Speed Manual',
      driveType: '4x2 / 4x4 Option',
      fuelType: 'Diesel',
      seatingCapacity: 5,
      payloadCapacityKg: 900,
      dimensions: '5165 mm (L) x 1750 mm (W) x 1815 mm (H)',
      wheelbase: '3090 mm',
      fuelTankCapacityLiters: 70,
      safetySummary: 'Disc Brakes, Hydraulic Brake Assist, ABS',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Passenger Comfort & Design',
        features: [
          'Spacious 5-Seater Ergonomic Cabin',
          'Air Conditioning with Rear Air Vents',
          'Heavy-Duty Rear Suspension for Smooth Transport',
          'Power Windows & Central Door Locking',
        ],
      },
    ]),
    warranty: '3 Years / 100,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/jac-t9-frison-brochure.pdf',
    seoTitle: 'JAC T9 Frison Pickup | Khyber Motors',
    metaDescription: 'Explore the dependable JAC T9 Frison double cabin pickup for passenger and commercial fleet transport.',
  },
  {
    name: 'JAC X200',
    fullTitle: 'JAC X200 Light Commercial Truck',
    slug: 'jac-x200',
    tagline: 'Compact & Efficient 1.15-Ton Cargo Deck Light Truck',
    category: 'TRUCKS',
    subcategory: 'LIGHT',
    categoryLabel: 'Light Truck',
    status: 'Published',
    isFlagship: false,
    isNew: true,
    mainImage: '',
    heroImage: '',
    altText: 'JAC Vehicle',
    gallery: JSON.stringify([]),
    colorOptions: JSON.stringify([{ name: 'Commercial White', hex: '#FFFFFF' }]),
    overview: 'The JAC X200 is an agile 1.15-ton payload light commercial deck truck engineered for urban goods delivery, retail transport, and small business logistics.',
    specs: JSON.stringify({
      engine: '2.8L 2771cc Diesel Engine',
      displacement: '2771 cc',
      horsepower: '77 HP @ 3600 RPM',
      torque: '174 Nm @ 2000 RPM',
      transmission: '5-Speed Manual Transmission',
      driveType: '4x2 Rear-Wheel Drive',
      fuelType: 'Diesel',
      seatingCapacity: 3,
      payloadCapacityKg: 1150,
      dimensions: '4840 mm (L) x 1750 mm (W) x 2040 mm (H)',
      wheelbase: '2470 mm',
      fuelTankCapacityLiters: 65,
      safetySummary: 'Reinforced Front Cabin, Vacuum Assisted Hydraulic Brakes',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Commercial Utility & Cabin',
        features: [
          'High Payload 1.15-Ton Cargo Deck',
          'Low Deck Loading Height for Rapid Cargo Transfer',
          'Ergonomic 3-Seater Cabin with Power Steering',
          'Heavy-Duty Leaf Spring Rear Suspension',
        ],
      },
    ]),
    warranty: '2 Years / 50,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/jac-x200-brochure.pdf',
    seoTitle: 'JAC X200 Light Truck | Khyber Motors',
    metaDescription: 'Efficient 1.15-ton deck light commercial truck for urban goods delivery and business logistics.',
  },
  {
    name: 'JAC 1020',
    fullTitle: 'JAC 1020 Light Commercial Truck',
    slug: 'jac-1020',
    tagline: 'Dependable 3.5-Ton Goods Transport Commercial Truck',
    category: 'TRUCKS',
    subcategory: 'LIGHT',
    categoryLabel: 'Light Truck',
    status: 'Published',
    isFlagship: false,
    isNew: false,
    mainImage: '',
    heroImage: '',
    altText: 'JAC Vehicle',
    gallery: JSON.stringify([]),
    colorOptions: JSON.stringify([{ name: 'Commercial White', hex: '#FFFFFF' }]),
    overview: 'The JAC 1020 light-duty commercial truck is built for medium-distance freight transport and urban distribution with a 3.5-ton load capacity.',
    specs: JSON.stringify({
      engine: '2.8L 2771cc Turbocharged Diesel Engine',
      displacement: '2771 cc',
      horsepower: '92 HP @ 3600 RPM',
      torque: '220 Nm @ 2200 RPM',
      transmission: '5-Speed Manual',
      driveType: '4x2 Rear-Wheel Drive',
      fuelType: 'Diesel',
      seatingCapacity: 3,
      payloadCapacityKg: 3500,
      dimensions: '5995 mm (L) x 2030 mm (W) x 2240 mm (H)',
      wheelbase: '3308 mm',
      fuelTankCapacityLiters: 80,
      safetySummary: 'Exhaust Brake, Hydraulic Dual-Circuit Brakes',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Chassis & Load Strength',
        features: [
          '3.5-Ton Rated Payload Capacity',
          'Heavy-Duty Riveted Steel Frame Chassis',
          'Tilting Driver Cabin for Quick Maintenance Access',
          'Dual Rear Wheels for Heavy Cargo Balance',
        ],
      },
    ]),
    warranty: '2 Years / 50,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/jac-1020-brochure.pdf',
    seoTitle: 'JAC 1020 3.5-Ton Commercial Truck | Khyber Motors',
    metaDescription: 'Workhorse 3.5-ton light commercial truck designed for freight and logistics.',
  },
  {
    name: 'JAC 1042',
    fullTitle: 'JAC 1042 14-Foot Cargo Deck Light Truck',
    slug: 'jac-1042',
    tagline: 'Heavy-Payload 14-Foot Cargo Deck Commercial Truck',
    category: 'TRUCKS',
    subcategory: 'LIGHT',
    categoryLabel: 'Light Truck',
    status: 'Published',
    isFlagship: false,
    isNew: true,
    mainImage: '',
    heroImage: '',
    altText: 'JAC Vehicle',
    gallery: JSON.stringify([]),
    colorOptions: JSON.stringify([{ name: 'Commercial White', hex: '#FFFFFF' }]),
    overview: 'The JAC 1042 is a high-capacity 14-foot deck commercial truck built for heavy freight distribution across intercity and local routes.',
    specs: JSON.stringify({
      engine: '2.8L Turbocharged Intercooled Diesel',
      displacement: '2771 cc',
      horsepower: '108 HP @ 3600 RPM',
      torque: '260 Nm @ 2000 RPM',
      transmission: '5-Speed Heavy Duty Manual',
      driveType: '4x2 Rear-Wheel Drive',
      fuelType: 'Diesel',
      seatingCapacity: 3,
      payloadCapacityKg: 4000,
      dimensions: '5990 mm (L) x 2080 mm (W) x 2300 mm (H)',
      wheelbase: '3360 mm',
      fuelTankCapacityLiters: 100,
      safetySummary: 'Air-Over-Hydraulic Brake System',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Transport & Drivetrain',
        features: [
          '14-Foot High Volume Cargo Deck Space',
          '4.0-Ton Rated Heavy Freight Payload',
          'Air-Over-Hydraulic Brakes for Safe Heavy Braking',
          'Spacious Driver Rest Cabin with Overhead Storage',
        ],
      },
    ]),
    warranty: '2 Years / 50,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/jac-1042-brochure.pdf',
    seoTitle: 'JAC 1042 14-Ft Deck Commercial Truck | Khyber Motors',
    metaDescription: '14-foot deck 4-ton commercial freight truck with turbocharged diesel engine.',
  },
  {
    name: 'JAC 1091',
    fullTitle: 'JAC 1091 17-Foot Commercial Cargo Truck',
    slug: 'jac-1091',
    tagline: 'High-Capacity 17-Foot Cargo Deck Transport Truck',
    category: 'TRUCKS',
    subcategory: 'LIGHT',
    categoryLabel: 'Light Truck',
    status: 'Published',
    isFlagship: false,
    isNew: false,
    mainImage: '',
    heroImage: '',
    altText: 'JAC Vehicle',
    gallery: JSON.stringify([]),
    colorOptions: JSON.stringify([{ name: 'Commercial White', hex: '#FFFFFF' }]),
    overview: 'The JAC 1091 commercial truck features a 17-foot deck capacity designed for heavy logistics, agricultural freight, and building material transport.',
    specs: JSON.stringify({
      engine: '3.9L 4-Cylinder Turbocharged Diesel',
      displacement: '3920 cc',
      horsepower: '125 HP @ 2800 RPM',
      torque: '380 Nm @ 1600-2000 RPM',
      transmission: '6-Speed Manual Transmission',
      driveType: '4x2 Rear-Wheel Drive',
      fuelType: 'Diesel',
      seatingCapacity: 3,
      payloadCapacityKg: 5500,
      dimensions: '6990 mm (L) x 2250 mm (W) x 2450 mm (H)',
      wheelbase: '3815 mm',
      fuelTankCapacityLiters: 120,
      safetySummary: 'Full Air Brake System, ABS',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Heavy Logistics Features',
        features: [
          '17-Foot Extended Length Cargo Deck',
          '5.5-Ton Rated Transport Payload Capacity',
          'Full Air Brake System for Maximum Safety',
          'Reinforced Dual Rear Axles & Heavy Leaf Springs',
        ],
      },
    ]),
    warranty: '2 Years / 50,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/jac-1091-brochure.pdf',
    seoTitle: 'JAC 1091 17-Ft Deck Truck | Khyber Motors',
    metaDescription: '17-foot cargo deck 5.5-ton commercial transport truck for heavy logistics.',
  },
  {
    name: 'JAC 1120',
    fullTitle: 'JAC 1120 20-Foot Heavy Duty Deck Truck',
    slug: 'jac-1120',
    tagline: 'Heavy Payload 20-Foot Commercial Transport Truck',
    category: 'TRUCKS',
    subcategory: 'LIGHT',
    categoryLabel: 'Light Truck',
    status: 'Published',
    isFlagship: false,
    isNew: true,
    mainImage: '',
    heroImage: '',
    altText: 'JAC Vehicle',
    gallery: JSON.stringify([]),
    colorOptions: JSON.stringify([{ name: 'Commercial White', hex: '#FFFFFF' }]),
    overview: 'The JAC 1120 commercial truck provides maximum deck space with its 20-foot platform length for bulk cargo and high-tonnage regional transport.',
    specs: JSON.stringify({
      engine: '4.1L Turbocharged Diesel Engine',
      displacement: '4100 cc',
      horsepower: '140 HP @ 2600 RPM',
      torque: '450 Nm @ 1500-1800 RPM',
      transmission: '6-Speed Heavy Duty Manual',
      driveType: '4x2 Rear-Wheel Drive',
      fuelType: 'Diesel',
      seatingCapacity: 3,
      payloadCapacityKg: 8000,
      dimensions: '7990 mm (L) x 2350 mm (W) x 2550 mm (H)',
      wheelbase: '4500 mm',
      fuelTankCapacityLiters: 150,
      safetySummary: 'Dual Circuit Full Air Brake System',
    }),
    features: JSON.stringify([
      {
        categoryName: 'High Capacity Chassis',
        features: [
          '20-Foot Heavy Duty Commercial Platform Deck',
          '8.0-Ton Rated Heavy Freight Payload Capacity',
          'Dual-Circuit Full Air Brakes with ABS',
          'High Torque 4.1L Turbo Diesel Powertrain',
        ],
      },
    ]),
    warranty: '2 Years / 50,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/jac-1120-brochure.pdf',
    seoTitle: 'JAC 1120 20-Ft Deck Truck | Khyber Motors',
    metaDescription: '20-foot deck 8.0-ton commercial transport truck for high-tonnage regional freight.',
  },
  {
    name: 'Dongfeng Prime Mover',
    fullTitle: 'Dongfeng Heavy-Duty Prime Mover 6x4 Tractor Truck',
    slug: 'dongfeng-prime-mover',
    tagline: 'High-Performance Heavy Haulage 6x4 Tractor Truck',
    category: 'DONGFENG',
    subcategory: 'HEAVY',
    subSubcategory: 'prime-movers',
    brand: 'Dongfeng',
    displayOrder: 8,
    categoryLabel: 'Dongfeng Heavy',
    status: 'Published',
    isFlagship: true,
    isNew: true,
    mainImage: '/uploads/dongfeng-prime-mover.jpg',
    heroImage: '/uploads/dongfeng-prime-mover.jpg',
    altText: 'Dongfeng Prime Mover',
    gallery: JSON.stringify(['/uploads/dongfeng-prime-mover.jpg']),
    colorOptions: JSON.stringify([
      { name: 'Dongfeng Crimson Red', hex: '#C8102E' },
      { name: 'Polar White', hex: '#FFFFFF' },
    ]),
    overview: 'The Dongfeng Heavy Prime Mover 6x4 tractor head is engineered for long-distance heavy container transport, bulk industrial haulage, and high-GCW logistics. Equipped with a high-torque Cummins diesel engine, synchronized 12-speed transmission, air suspension driver cab, and reinforced dual rear drive axles.',
    specs: JSON.stringify({
      engine: 'Cummins 11L / 13L High Output Turbo Diesel',
      displacement: '10800 cc',
      horsepower: '420 - 450 HP @ 1900 RPM',
      torque: '2100 Nm @ 1100-1400 RPM',
      transmission: 'Fast 12-Speed Manual with Overdrive',
      driveType: '6x4 Dual Rear Drive Axle',
      fuelType: 'Diesel',
      seatingCapacity: 2,
      payloadCapacityKg: 40000,
      towingCapacityKg: '55,000 kg GCW',
      dimensions: '6960 mm (L) x 2500 mm (W) x 3850 mm (H)',
      wheelbase: '3300 + 1350 mm',
      fuelTankCapacityLiters: 600,
      safetySummary: 'Dual-Circuit Full Air Brakes, ABS, Exhaust Retarder, Airbag Suspended Cab',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Powertrain & Chassis',
        features: [
          'Cummins High-Output Electronic Fuel Injection Diesel',
          'Fast 12-Speed Synchronized Transmission with Low Creep Ratio',
          'Heavy-Duty 13-Ton Tandem Drive Axles with Inter-Wheel Locks',
          'High Capacity 600L Aluminum Long-Haul Fuel Tank',
        ],
      },
    ]),
    warranty: '2 Years / 150,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/dongfeng-prime-mover-brochure.pdf',
    seoTitle: 'Dongfeng Heavy Prime Mover 6x4 Tractor Truck | Khyber Motors',
    metaDescription: 'High-performance Dongfeng Prime Mover 6x4 heavy tractor truck for long-distance high-GCW logistics.',
  },
  {
    name: 'Dongfeng Rigid Truck',
    fullTitle: 'Dongfeng Heavy-Duty Rigid Dump & Cargo Truck',
    slug: 'dongfeng-rigid',
    tagline: 'Heavy-Duty Industrial Multi-Axle Rigid Cargo & Dump Truck',
    category: 'DONGFENG',
    subcategory: 'HEAVY',
    subSubcategory: 'rigid',
    brand: 'Dongfeng',
    displayOrder: 9,
    categoryLabel: 'Dongfeng Heavy',
    status: 'Published',
    isFlagship: false,
    isNew: true,
    mainImage: '/uploads/dongfeng-rigid-dump.jpg',
    heroImage: '/uploads/dongfeng-rigid-dump.jpg',
    altText: 'Dongfeng Heavy Rigid Truck',
    gallery: JSON.stringify(['/uploads/dongfeng-rigid-dump.jpg']),
    colorOptions: JSON.stringify([
      { name: 'Industrial Ochre', hex: '#D97706' },
      { name: 'Commercial White', hex: '#FFFFFF' },
    ]),
    overview: 'The Dongfeng Heavy Rigid Truck is engineered for mining, quarry transport, bulk construction aggregates, and heavy payload regional freight.',
    specs: JSON.stringify({
      engine: 'Cummins 8.9L / 9.5L Turbocharged Diesel',
      displacement: '8900 cc',
      horsepower: '340 - 375 HP @ 2100 RPM',
      torque: '1500 Nm @ 1200-1600 RPM',
      transmission: '10-Speed Heavy Duty Manual',
      driveType: '6x4 / 8x4 Rigid Multi-Axle',
      fuelType: 'Diesel',
      seatingCapacity: 2,
      payloadCapacityKg: 25000,
      dimensions: '8500 mm (L) x 2500 mm (W) x 3450 mm (H)',
      wheelbase: '3800 + 1350 mm',
      fuelTankCapacityLiters: 400,
      safetySummary: 'Full Air Brakes, Spring Brake Chambers, High Ground Clearance',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Industrial Heavy Duty Chassis',
        features: [
          'High-Tensile Reinforced Double-Layer Straight Rail Frame',
          'Multi-Leaf Heavy-Gauge Steel Spring Front and Rear Suspension',
          'Heavy-Duty Hub-Reduction Planetary Drive Axles',
        ],
      },
    ]),
    warranty: '2 Years / 100,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/dongfeng-rigid-brochure.pdf',
    seoTitle: 'Dongfeng Rigid Heavy Dump & Cargo Truck | Khyber Motors',
    metaDescription: 'Rugged Dongfeng Rigid heavy truck for mining, construction, and heavy industrial freight.',
  },
  {
    name: 'Dongfeng Light Truck',
    fullTitle: 'Dongfeng Light Commercial Cargo Truck',
    slug: 'dongfeng-light',
    tagline: 'Agile Urban Freight & Commercial Logistics Cargo Truck',
    category: 'DONGFENG',
    subcategory: 'LIGHT',
    subSubcategory: null,
    brand: 'Dongfeng',
    displayOrder: 10,
    categoryLabel: 'Dongfeng Light',
    status: 'Published',
    isFlagship: false,
    isNew: true,
    mainImage: '/uploads/dongfeng-light-truck.jpg',
    heroImage: '/uploads/dongfeng-light-truck.jpg',
    altText: 'Dongfeng Light Commercial Truck',
    gallery: JSON.stringify(['/uploads/dongfeng-light-truck.jpg']),
    colorOptions: JSON.stringify([
      { name: 'Polar White', hex: '#FFFFFF' },
      { name: 'Silver Metallic', hex: '#9CA3AF' },
    ]),
    overview: 'Dongfeng Light Commercial Truck built for urban cargo distribution, e-commerce dispatch, and regional supply chain transport.',
    specs: JSON.stringify({
      engine: '3.0L Turbocharged Intercooled Diesel',
      displacement: '2970 cc',
      horsepower: '140 HP @ 3200 RPM',
      torque: '380 Nm @ 1600-2600 RPM',
      transmission: '6-Speed Manual Transmission',
      driveType: '4x2 Rear-Wheel Drive',
      fuelType: 'Diesel',
      seatingCapacity: 3,
      payloadCapacityKg: 4500,
      dimensions: '5995 mm (L) x 2100 mm (W) x 2320 mm (H)',
      wheelbase: '3308 mm',
      fuelTankCapacityLiters: 120,
      safetySummary: 'Hydraulic / Pneumatic ABS Brakes, High Visibility LED Daytime Lamps',
    }),
    features: JSON.stringify([
      {
        categoryName: 'Logistics Efficiency',
        features: [
          'High Fuel Economy 3.0L Common Rail Turbo Diesel Powertrain',
          '6-Speed Overdrive Manual Gearbox for Highway & City Cruising',
          '14-Foot Drop-Side Rigid Steel Cargo Bed',
        ],
      },
    ]),
    warranty: '2 Years / 60,000 KM Manufacturer Warranty',
    brochureAvailable: true,
    brochureUrl: '/brochures/dongfeng-light-brochure.pdf',
    seoTitle: 'Dongfeng Light Commercial Cargo Truck | Khyber Motors',
    metaDescription: 'Nimble and fuel-efficient Dongfeng Light Commercial Truck for urban distribution.',
  },
];

async function seed() {
  console.log('🌱 Starting database seeding...');

  try {
    // 1. Seed Primary Admin User using environment variables ADMIN_EMAIL and ADMIN_PASSWORD
    const adminEmail = (process.env.ADMIN_EMAIL || 'muawiakhan000@gmail.com').toLowerCase().trim();
    const rawPassword = process.env.ADMIN_PASSWORD || 'Ameer100$';
    const passwordHash = await bcrypt.hash(rawPassword, 10);

    const admin = await prisma.adminUser.upsert({
      where: { email: adminEmail },
      update: {
        passwordHash,
        isPrimary: true,
        isActive: true,
      },
      create: {
        email: adminEmail,
        passwordHash,
        name: 'Primary Super Admin',
        role: 'SUPER_ADMIN',
        isPrimary: true,
        isActive: true,
      },
    });
    console.log(`✅ Primary Admin user seeded: ${admin.email}`);

    // 2. Seed Vehicles (Do NOT overwrite existing vehicle data or images if already in DB)
    for (const v of defaultVehicles) {
      const existing = await prisma.vehicle.findUnique({ where: { slug: v.slug } });
      if (!existing) {
        const vehicle = await prisma.vehicle.create({ data: v });
        console.log(`✅ Vehicle seeded: ${vehicle.name} (${vehicle.slug})`);
      }
    }

    // 3. Seed Page Content
    const homeContent = {
      hero: {
        eyebrow: 'KHYBER MOTORS',
        title: 'Built for Work. Ready for More.',
        description: 'Discover powerful, dependable commercial vehicles and double cabin pickups designed to perform on every road.',
        primaryCtaText: 'Explore Vehicles',
        primaryCtaLink: '/vehicles',
        secondaryCtaText: 'Contact Us',
        secondaryCtaLink: '/contact',
        heroImage: '',
        heroImages: [],
      },
    };

    await prisma.pageContent.upsert({
      where: { key: 'home' },
      update: { data: JSON.stringify(homeContent) },
      create: { key: 'home', data: JSON.stringify(homeContent) },
    });
    console.log('✅ Home page content seeded.');

    const contactContent = {
      name: 'Khyber Motors',
      shortName: 'Khyber Motors',
      status: 'Authorized 3S Dealership (Sales, Service & Spare Parts)',
      tagline: 'Engineered for Performance. Built for Pakistan.',
      footerText: 'Khyber Pakhtunkhwa’s premier 3S Dealership for double cabin pickup trucks, commercial logistics vehicles, and modern crossover SUVs.',
      address: 'XHQQ+8GV, Ring Road Sohailabad, near Kakakhel CNG, Hazara Khawani, Peshawar, 25000, Pakistan',
      mapLink: 'https://www.google.com/maps/search/?api=1&query=XHQQ%2B8GV%2C+Ring+Road+Sohailabad%2C+near+Kakakhel+CNG%2C+Hazara+Khawani%2C+Peshawar%2C+25000%2C+Pakistan',
      mapEmbedUrl: 'https://maps.google.com/maps?q=XHQQ%2B8GV%2C+Ring+Road+Sohailabad%2C+near+Kakakhel+CNG%2C+Hazara+Khawani%2C+Peshawar%2C+25000%2C+Pakistan&t=&z=16&ie=UTF8&iwloc=&output=embed',
      plusCode: 'XHQQ+8GV, Peshawar',
      city: 'Peshawar',
      province: 'Khyber Pakhtunkhwa',
      postalCode: '25000',
      phone: '+92 (091) 5840900',
      salesDirect: '+92 300 1234567',
      serviceDirect: '+92 300 7654321',
      whatsapp: '+92 300 0000000',
      email: 'muawiakhan000@gmail.com',
      social: {
        tiktok: 'https://tiktok.com/@khybermotors',
        instagram: 'https://instagram.com/khybermotors',
        facebook: 'https://facebook.com/khybermotors',
        whatsapp: 'https://wa.me/923000000000',
      },
      businessHours: [
        { days: 'Monday – Saturday', hours: '9:00 AM – 7:00 PM' },
        { days: 'Sunday', hours: 'Emergency Service Only (10:00 AM – 4:00 PM)' },
      ],
      departments: [
        { name: 'Showroom & Sales', contact: '+92 (091) 5840901', timing: '9:00 AM – 7:00 PM' },
        { name: 'Authorized 3S Workshop', contact: '+92 (091) 5840902', timing: '8:30 AM – 5:30 PM' },
        { name: 'Genuine Spare Parts', contact: '+92 (091) 5840903', timing: '9:00 AM – 6:00 PM' },
        { name: 'Fleet & Corporate Sales', contact: '+92 (091) 5840904', timing: '9:00 AM – 6:00 PM' },
      ],
    };

    await prisma.pageContent.upsert({
      where: { key: 'contact' },
      update: { data: JSON.stringify(contactContent) },
      create: { key: 'contact', data: JSON.stringify(contactContent) },
    });
    console.log('✅ Contact page content seeded.');

    console.log('🎉 Database seeding completed successfully!');
  } catch (error) {
    console.error('❌ Seeding notice:', error.message);
  } finally {
    if (prisma && typeof prisma.$disconnect === 'function') {
      await prisma.$disconnect().catch(() => null);
    }
  }
}

seed();
